export const vars = {
  background: {
    informativeOnSubtle: ['eq'],
    positiveOnSubtle: ['er'],
    warningOnSubtle: ['es'],
    negativeOnSubtle: ['et'],
    brandOnSubtle: ['eu'],
    default: ['jw'],
    neutralStrong: ['jx'],
    neutralOnSubtle: ['jy'],
    informativeStrong: ['jz'],
    positiveStrong: ['ka'],
    warningStrong: ['kb'],
    negativeStrong: ['kc'],
    brandStrong: ['kd'],
  },
  action: {
    primarySubtle: ['ev'],
    primarySubtleHover: ['ew'],
    primarySubtleActive: ['ex'],
    primarySubtleSelected: ['ey'],
    alertSubtle: ['ez'],
    alertSubtleHover: ['fa'],
    alertSubtleActive: ['fb'],
    alertSubtleSelected: ['fc'],
    backgroundModeless: ['fd'],
    primary: ['ke'],
    primaryHover: ['kf'],
    primaryActive: ['kg'],
    primarySelected: ['kh'],
    neutral: ['ki'],
    neutralHover: ['kj'],
    neutralActive: ['kk'],
    neutralSelected: ['kl'],
    neutralSubtle: ['km'],
    neutralSubtleHover: ['kn'],
    neutralSubtleActive: ['ko'],
    neutralSubtleSelected: ['kp'],
    ghost: ['kq'],
    ghostHover: ['kr'],
    ghostActive: ['ks'],
    ghostSelected: ['kt'],
    inverted: ['ku'],
    alert: ['kv'],
    alertHover: ['kw'],
    alertActive: ['kx'],
    alertSelected: ['ky'],
    borderActive: ['kz'],
    borderNeutral: ['la'],
    borderNeutralHover: ['lb'],
    borderNeutralActive: ['lc'],
    borderNeutralSelected: ['ld'],
    borderAlert: ['le'],
  },
  nonSemantic: {
    borderGreyStrong: ['fe'],
    backgroundRedMuted: ['ff'],
    backgroundRedOnSubtle: ['fg'],
    backgroundRaspberryMuted: ['fh'],
    backgroundRaspberryOnSubtle: ['fi'],
    backgroundMagentaMuted: ['fj'],
    backgroundMagentaOnSubtle: ['fk'],
    backgroundPurpleMuted: ['fl'],
    backgroundPurpleOnSubtle: ['fm'],
    backgroundGrapeMuted: ['fn'],
    backgroundGrapeOnSubtle: ['fo'],
    backgroundVioletMuted: ['fp'],
    backgroundVioletOnSubtle: ['fq'],
    backgroundBlueMuted: ['fr'],
    backgroundBlueOnSubtle: ['fs'],
    backgroundCyanMuted: ['ft'],
    backgroundCyanOnSubtle: ['fu'],
    backgroundTealMuted: ['fv'],
    backgroundTealOnSubtle: ['fw'],
    backgroundAquamarineMuted: ['fx'],
    backgroundAquamarineOnSubtle: ['fy'],
    backgroundGreenMuted: ['fz'],
    backgroundGreenOnSubtle: ['ga'],
    backgroundEmeraldMuted: ['gb'],
    backgroundEmeraldOnSubtle: ['gc'],
    backgroundOrangeMuted: ['gd'],
    backgroundOrangeOnSubtle: ['ge'],
    contentWhitePrimary: ['mq'],
    contentRedPrimary: ['mr'],
    contentRaspberryPrimary: ['ms'],
    contentMagentaPrimary: ['mt'],
    contentPurplePrimary: ['mu'],
    contentGrapePrimary: ['mv'],
    contentVioletPrimary: ['mw'],
    contentBluePrimary: ['mx'],
    contentCyanPrimary: ['my'],
    contentTealPrimary: ['mz'],
    contentAquamarinePrimary: ['na'],
    contentGreenPrimary: ['nb'],
    contentEmeraldPrimary: ['nc'],
    contentOrangePrimary: ['nd'],
    backgroundRedStrong: ['ne'],
    backgroundRaspberryStrong: ['nf'],
    backgroundMagentaStrong: ['ng'],
    backgroundPurpleStrong: ['nh'],
    backgroundGrapeStrong: ['ni'],
    backgroundVioletStrong: ['nj'],
    backgroundBlueStrong: ['nk'],
    backgroundCyanStrong: ['nl'],
    backgroundTealStrong: ['nm'],
    backgroundAquamarineStrong: ['nn'],
    backgroundGreenStrong: ['no'],
    backgroundEmeraldStrong: ['np'],
    backgroundOrangeStrong: ['nq'],
  },
  global: {
    coolGrey: [
      '',
      [
        [1, 'gi'],
        [5, 'gj'],
      ],
      [
        [2, 'gh'],
        [3, 'gg'],
        [4, 'gf'],
      ],
    ],
    coolGreyAlphaGreya: [
      '',
      [
        [1, 'gk'],
        [3, 'gl'],
        [4, 'gm'],
        [5, 'gn'],
        [6, 'go'],
        [7, 'gp'],
      ],
    ],
    neutralGrey: ['', null, [[4, 'gq']]],
    whiteAlphaTransparent: ['gr'],
    whiteAlphaWhitea2: ['', null, [[2, 'gs']]],
    whiteAlphaWhitea0: ['', null, [[0, 'gt']]],
    whiteAlphaWhitea: [
      'hc',
      null,
      [
        [1, 'hb'],
        [2, 'ha'],
        [4, 'gz'],
        [5, 'gy'],
        [6, 'gx'],
        [7, 'gw'],
        [8, 'gv'],
        [9, 'gu'],
      ],
    ],
    blue: [
      'he',
      [
        [1, 'hf'],
        [2, 'hg'],
      ],
      [[1, 'hd']],
    ],
    green: [
      'hi',
      [
        [1, 'hj'],
        [2, 'hk'],
      ],
      [[1, 'hh']],
    ],
    red: [
      'ho',
      [
        [1, 'hp'],
        [2, 'hq'],
        [3, 'hr'],
      ],
      [
        [1, 'hn'],
        [2, 'hm'],
        [3, 'hl'],
      ],
    ],
    orange: [
      'ht',
      [
        [1, 'hu'],
        [2, 'hv'],
      ],
      [[1, 'hs']],
    ],
    raspberry: [
      'hx',
      [
        [1, 'hy'],
        [2, 'hz'],
      ],
      [[1, 'hw']],
    ],
    magenta: [
      'ib',
      [
        [1, 'ic'],
        [2, 'id'],
      ],
      [[1, 'ia']],
    ],
    purple: [
      'if',
      [
        [1, 'ig'],
        [2, 'ih'],
      ],
      [[1, 'ie']],
    ],
    grape: [
      'ij',
      [
        [1, 'ik'],
        [2, 'il'],
      ],
      [[1, 'ii']],
    ],
    violet: [
      'ip',
      [
        [1, 'iq'],
        [2, 'ir'],
        [3, 'is'],
      ],
      [
        [1, 'io'],
        [2, 'in'],
        [3, 'im'],
      ],
    ],
    cyan: [
      'iu',
      [
        [1, 'iv'],
        [2, 'iw'],
      ],
      [[1, 'it']],
    ],
    teal: ['', [[2, 'iy']], [[1, 'ix']]],
    aquamarine: [
      'ja',
      [
        [1, 'jb'],
        [2, 'jc'],
      ],
      [[1, 'iz']],
    ],
    emerald: [
      'je',
      [
        [1, 'jf'],
        [2, 'jg'],
      ],
      [[1, 'jd']],
    ],
  },
  radius: { xs: ['jh'], s: ['ji'], m: ['jj'], l: ['jk'], xxl: ['jl'] },
  content: {
    primary: ['jm'],
    secondary: ['jn'],
    invertedPrimary: ['jo'],
    informativePrimary: ['jp'],
    positivePrimary: ['jq'],
    warningPrimary: ['jr'],
    negativePrimary: ['js'],
    brandPrimary: ['jt'],
  },
  border: { default: ['ju'], brandStrong: ['jv'] },
  semantic: {
    brand: [
      'li',
      [
        [1, 'lj'],
        [2, 'lk'],
        [3, 'll'],
      ],
      [
        [1, 'lh'],
        [2, 'lg'],
        [3, 'lf'],
      ],
    ],
    neutral: [
      '',
      [
        [1, 'lp'],
        [5, 'lq'],
      ],
      [
        [2, 'lo'],
        [3, 'ln'],
        [4, 'lm'],
      ],
    ],
    neutralAlphaNeutrala: [
      '',
      [
        [1, 'lr'],
        [3, 'ls'],
        [4, 'lt'],
        [5, 'lu'],
        [6, 'lv'],
        [7, 'lw'],
      ],
    ],
    informative: [
      'ly',
      [
        [1, 'lz'],
        [2, 'ma'],
      ],
      [[1, 'lx']],
    ],
    positive: [
      'mc',
      [
        [1, 'md'],
        [2, 'me'],
      ],
      [[1, 'mb']],
    ],
    warning: [
      'mg',
      [
        [1, 'mh'],
        [2, 'mi'],
      ],
      [[1, 'mf']],
    ],
    negative: [
      'mm',
      [
        [1, 'mn'],
        [2, 'mo'],
        [3, 'mp'],
      ],
      [
        [1, 'ml'],
        [2, 'mk'],
        [3, 'mj'],
      ],
    ],
  },
}
