export const vars = {
  content: {
    _: { primary: 0, secondary: 1 },
    default: ['vh', 'xl'],
    inverted: ['xj', 'xd'],
    informative: ['wz', 'ws'],
    positive: ['wx', 'wp'],
    warning: ['wm', 'wh'],
    negative: ['wk', 'wg'],
    brand: ['we', 'wc'],
  },
  border: {
    _: { strong: 0, subtle: 1 },
    default: ['wa', 'vy'],
    inverted: ['wn', 'jh'],
    informative: ['vw', 'vv'],
    positive: ['vu', 'vt'],
    warning: ['vs', 'vr'],
    negative: ['vq', 'vn'],
    brand: ['vm', 'xk'],
  },
  background: {
    _: { strong: 0, muted: 1, soft: 2, subtle: 3, surface: 4 },
    default: ['xf', 'sg', 'sv', 'sb', 'sd'],
    inverted: ['vl', 'st', 'sx', 'sp', 'sr'],
    neutral: ['vi', 'xe', 'wu', 'xa', 'xg'],
    informative: ['wt', 'wj', 'wo', 'wy', 'wi'],
    positive: ['vz', 'wf', 'wl', 'wb', 've'],
    warning: ['vx', 'wd', 'vd', 'vc', 'vb'],
    negative: ['va', 'uz', 'uw', 'uv', 'ur'],
    brand: ['up', 'un', 'um', 'ui', 'ug'],
  },
  action: {
    _: {
      normal: 0,
      hover: 1,
      active: 2,
      selected: 3,
      subtleNormal: 4,
      subtleHover: 5,
      subtleActive: 6,
      subtleSelected: 7,
    },
    primary: ['uf', 'ue', 'ub', 'ua', 'tz', 'ty', 'tx', 'tw'],
    neutral: ['tv', 'tu', 'tt', 'ts', 'tr', 'tq', 'tp', 'to'],
    system: ['ti', 'tm', 'tf', 'sz', 'uj', 'ut', 'ux', 'ru'],
    inverted: ['se', 'so', 'sl', 'si', 'ry', 'sj', 'sm', 'rw'],
    alert: ['rt', 'rs', 'rr', 'rq', 'rp', 'ro', 'rn', 'rm'],
  },
  inputBorder: {
    _: { default: 0 },
    normal: ['qz'],
    hover: ['qx'],
    active: ['qv'],
    selected: ['qt'],
    neutralNormal: ['qr'],
    neutralHover: ['qp'],
    neutralActive: ['qn'],
    neutralSelected: ['ql'],
    alert: ['qj'],
  },
  standalone: {
    _: { default: 0 },
    modal: ['qh'],
    dimmer: ['qb'],
    foregroundSubtle: ['rj'],
    foreground: ['jc'],
    foregroundContent: ['iv'],
  },
  semantic: {
    _i: 1,
    brand: [
      'po',
      ['pq', 'pk', 'ps', 'pu'],
      ['pm', 'vp', 'pj', 'ph', 'xh', 'xb', 'vk', 'vg'],
    ],
    neutral: [
      'os',
      ['pc', 'wv', 'wq', 'pa'],
      ['oy', 'pe', 'ou', 'ok', 'oq', 'ow', 'om', 'nw'],
    ],
    neutralAlpha: [
      'of',
      ['oj', 'oa', 'oo', 'og'],
      ['oc', 'nz', 'nv', 'nt', 'nr', 'np', 'nn', 'nl'],
    ],
    informative: [
      'nb',
      ['nd', 'nf', 'nh', 'nj'],
      ['mz', 'mx', 'mv', 'mt', 'mr', 'mp', 'mn', 'ml'],
    ],
    positive: [
      'mb',
      ['md', 'mf', 'mh', 'mj'],
      ['lz', 'lx', 'lv', 'lt', 'lr', 'lp', 'ln', 'll'],
    ],
    warning: [
      'lb',
      ['ld', 'lf', 'lh', 'lj'],
      ['kz', 'kx', 'kv', 'kt', 'kr', 'kp', 'kn', 'kl'],
    ],
    negative: [
      'kb',
      ['kd', 'kf', 'kh', 'kj'],
      ['jz', 'jx', 'jv', 'jt', 'jr', 'jp', 'jn', 'jl'],
    ],
  },
  nonSemanticContent: {
    _: { primary: 0, secondary: 1 },
    grey: ['jj', 'jg'],
    white: ['je', 'jb'],
    red: ['iz', 'ix'],
    raspberry: ['iu', 'is'],
    magenta: ['iq', 'io'],
    purple: ['im', 'ik'],
    grape: ['ii', 'ig'],
    violet: ['ie', 'ic'],
    blue: ['ia', 'hy'],
    cyan: ['hw', 'hu'],
    teal: ['hs', 'hq'],
    aquamarine: ['ho', 'hm'],
    green: ['hk', 'hi'],
    emerald: ['hg', 'he'],
    orange: ['hc', 'ha'],
  },
  nonSemanticBorder: {
    _: { strong: 0, subtle: 1 },
    grey: ['gx', 'gv'],
    white: ['gs', 'gq'],
    red: ['gn', 'gl'],
    raspberry: ['gi', 'gg'],
    magenta: ['gd', 'gb'],
    purple: ['fy', 'fw'],
    grape: ['ft', 'fr'],
    violet: ['fo', 'fm'],
    blue: ['fj', 'fh'],
    cyan: ['fe', 'fc'],
    teal: ['ez', 'ex'],
    aquamarine: ['eu', 'es'],
    green: ['ep', 'en'],
    emerald: ['pg', 'pl'],
    orange: ['pi', 'vf'],
  },
  nonSemanticBackground: {
    _: { strong: 0, muted: 1, soft: 2, subtle: 3, surface: 4 },
    grey: ['xi', 'vo', 'vj', 'pd', 'pb'],
    white: ['xc', 'ww', 'ov', 'ot', 'wr'],
    red: ['pf', 'on', 'ol', 'oz', 'ox'],
    raspberry: ['ob', 'nx', 'or', 'op', 'ny'],
    magenta: ['oi', 'oh', 'od', 'uq', 'uy'],
    purple: ['oe', 'us', 'uh', 'uo', 'uu'],
    grape: ['uk', 'tl', 'tk', 'ul', 'uc'],
    violet: ['tg', 'te', 'ud', 'tn', 'tb'],
    blue: ['ta', 'tj', 'th', 'ss', 'sq'],
    cyan: ['td', 'tc', 'sf', 'sc', 'sy'],
    teal: ['su', 'rx', 'sn', 'sw', 'sh'],
    aquamarine: ['rv', 'sa', 'sk', 'rz', 'ku'],
    green: ['la', 'lg', 'kw', 'km', 'ks'],
    emerald: ['ky', 'ko', 'ke', 'kk', 'kq'],
    orange: ['kg', 'jw', 'kc', 'ki', 'jy'],
  },
  global: {
    _i: 1,
    coolGrey: [
      'jf',
      ['jq', 'ka', 'ju', 'jo'],
      ['jm', 'js', 'ji', 'iw', 'jd', 'jk', 'iy', 'rh'],
    ],
    coolGreyAlpha: [
      'rg',
      ['rd', 'ri', 'ja', 'rl'],
      ['rk', 're', 'qy', 'rc', 'rf', 'ra', 'qq', 'qw'],
    ],
    neutralGrey: [
      'qu',
      ['qo', 'qi', 'qs', 'rb'],
      ['qk', 'qd', 'qg', 'qm', 'qe', 'py', 'qc', 'qf'],
    ],
    neutralGreyAlpha: [
      'pv',
      ['qa', 'px', 'pt', 'pz'],
      ['pn', 'pr', 'pw', 'pp', 'fz', 'ge', 'gj', 'ga'],
    ],
    warmGrey: [
      'fl',
      ['fu', 'gc', 'fx', 'fs'],
      ['fq', 'fv', 'fn', 'ff', 'fk', 'fp', 'fg', 'ey'],
    ],
    warmGreyAlpha: [
      'ew',
      ['er', 'fa', 'fi', 'fd'],
      ['fb', 'et', 'el', 'eq', 'ev', 'em', 'no', 'nu'],
    ],
    whiteAlpha: [
      'ms',
      [
        'nc',
        'mw',
        'mq',
        'na',
        'nk',
        'ne',
        'my',
        'ni',
        'ns',
        'nm',
        'ng',
        'nq',
        'eo',
      ],
      [],
    ],
    blue: [
      'ma',
      ['mk', 'mu', 'mo', 'mi'],
      ['mg', 'mm', 'mc', 'ls', 'ly', 'me', 'lu', 'lk'],
    ],
    green: [
      'li',
      ['lc', 'lm', 'lw', 'lq'],
      ['lo', 'le', 'ek', 'ej', 'ei', 'eh', 'eg', 'ef'],
    ],
    red: [
      'ea',
      ['eb', 'ec', 'ed', 'ee'],
      ['dz', 'dy', 'dx', 'dw', 'dv', 'du', 'dt', 'ds'],
    ],
    orange: [
      'dn',
      ['do', 'dp', 'dq', 'dr'],
      ['dm', 'dl', 'dk', 'dj', 'in', 'it', 'di', 'ip'],
    ],
    raspberry: [
      'hx',
      ['ih', 'ir', 'il', 'if'],
      ['id', 'ij', 'hz', 'hp', 'hv', 'ib', 'hr', 'hh'],
    ],
    magenta: [
      'hf',
      ['gz', 'hj', 'ht', 'hn'],
      ['hl', 'hb', 'gt', 'gy', 'hd', 'gu', 'gm', 'gr'],
    ],
    purple: [
      'gp',
      ['gk', 'gf', 'go', 'gw'],
      ['gh', 'dh', 'dg', 'df', 'de', 'dd', 'dc', 'db'],
    ],
    grape: [
      'cw',
      ['cx', 'cy', 'cz', 'da'],
      ['cv', 'cu', 'ct', 'cs', 'cr', 'cq', 'cp', 'co'],
    ],
    violet: [
      'cj',
      ['ck', 'cl', 'cm', 'cn'],
      ['ci', 'ch', 'cg', 'cf', 'ce', 'cd', 'cc', 'cb'],
    ],
    cyan: [
      'bw',
      ['bx', 'by', 'bz', 'ca'],
      ['bv', 'bu', 'bt', 'bs', 'br', 'bq', 'bp', 'bo'],
    ],
    teal: [
      'bj',
      ['bk', 'bl', 'bm', 'bn'],
      ['bi', 'bh', 'bg', 'bf', 'be', 'bd', 'bc', 'bb'],
    ],
    aquamarine: [
      'aw',
      ['ax', 'ay', 'az', 'ba'],
      ['av', 'au', 'at', 'as', 'ar', 'aq', 'ap', 'ao'],
    ],
    emerald: [
      'aj',
      ['ak', 'al', 'am', 'an'],
      ['ai', 'ah', 'ag', 'af', 'ae', 'ad', 'ac', 'ab'],
    ],
  },
}
